on:
  push:
    branches:
      - master
      - feature/*

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: production

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Cache Maven Repos
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Maven Clean And Install
        run: |
          mvn clean
          mvn install -DskipTests=true && mvn package -DskipTests=true
          echo '=====打包成功====='  

      - name: Build Docker Images
        run: |
          echo '=====开始构建镜像====='
          cd app  
          mvn docker:build
          echo '=====构建成功=====' 

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Images tag and push
        run: |
          docker tag coin-pusher:latest yangcaiwang/coin-pusher:latest
          docker push yangcaiwang/coin-pusher:latest
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:

      - name: deploy by shh
        env:
          PROJECTS: "app;9000"
          TAG: latest
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /opt/coin-pusher
            chmod +x deploy.sh
            ./deploy.sh ${{ secrets.DOCKER_USERNAME }} ${{ secrets.DOCKER_PASSWORD }} ${PROJECTS} ${TAG}
            echo '执行完成'